---
apiVersion: batch/v1
kind: Job
metadata:
  name: lobsters-db-schema-load
spec:
  template:
    metadata:
      namespace: lobsters
      name: lobsters-db-schema-load
      labels:
        task: db-schema-load
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:testing
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: database-url
          command:
            - "/usr/local/bundle/bin/rake"
            - "db:schema:load"
      restartPolicy: Never
