apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lobsters
  name: lobsters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lobsters
  template:
    metadata:
      labels:
        app: lobsters
    spec:
      containers:
        - name: lobsters
          image: kelseyhightower/lobsters:2.0.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: database-url
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lobsters
  name: lobsters
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: lobsters
  type: LoadBalancer
