---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lobsters
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mysql
  template:
    metadata:
      labels:
        app: mysql
      name: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.6.32
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: root-password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lobsters
                  key: mysql-password
            - name: MYSQL_USER
              value: lobsters
            - name: MYSQL_DATABASE
              value: lobsters
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      volumes:
        - name: "mysql"
          persistentVolumeClaim:
            claimName: mysql
---
apiVersion: v1
kind: Service
metadata:
  namespace: lobsters
  labels:
    app: mysql
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
