---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: lobsters
spec:
  storageClassName: ase-node-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
